// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginTestTokenResponse,
  OrganizationsCreateOrganizationData,
  OrganizationsCreateOrganizationResponse,
  OrganizationsDeleteOrganizationData,
  OrganizationsDeleteOrganizationResponse,
  OrganizationsReadOrganizationData,
  OrganizationsReadOrganizationResponse,
  OrganizationsReadOrganizationsData,
  OrganizationsReadOrganizationsResponse,
  OrganizationsUpdateOrganizationData,
  OrganizationsUpdateOrganizationResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  ServeIndex1Response,
  ServeIndex2Response,
  ServeIndex3Response,
  ServeIndex4Response,
  ServeIndex5Response,
  ServeIndex6Response,
  ServeIndex7Response,
  ServeIndex8Response,
  ServeIndexResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserMeResponse,
  UsersDeleteUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersReadUserMeResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersUpdateUserData,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdateUserResponse,
  UtilsHealthCheckResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  WorkflowsCreateWorkflowData,
  WorkflowsCreateWorkflowResponse,
  WorkflowsDeleteWorkflowData,
  WorkflowsDeleteWorkflowResponse,
  WorkflowsReadWorkflowData,
  WorkflowsReadWorkflowResponse,
  WorkflowsReadWorkflowsData,
  WorkflowsReadWorkflowsResponse,
  WorkflowsUpdateWorkflowData,
  WorkflowsUpdateWorkflowGraphData,
  WorkflowsUpdateWorkflowGraphResponse,
  WorkflowsUpdateWorkflowResponse,
} from "./types.gen"

export class DefaultService {
  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex(): CancelablePromise<ServeIndexResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/workflow/{workflow_id}",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex1(): CancelablePromise<ServeIndex1Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/workflows",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex2(): CancelablePromise<ServeIndex2Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/recover-password",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex3(): CancelablePromise<ServeIndex3Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/signup",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex4(): CancelablePromise<ServeIndex4Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/admin",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex5(): CancelablePromise<ServeIndex5Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/home",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex6(): CancelablePromise<ServeIndex6Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/settings",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex7(): CancelablePromise<ServeIndex7Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/login",
    })
  }

  /**
   * Serve Index
   * Serve the frontend application.
   *
   * index.html must not be cached: it names the hashed bundle, so a cached copy
   * keeps a browser on the previous build after a rebuild (which looks like a
   * fix "not working"). The hashed assets under /assets are safe to cache.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static serveIndex8(): CancelablePromise<ServeIndex8Response> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/",
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class OrganizationsService {
  /**
   * Read Organizations
   * Retrieve organizations.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns OrganizationsPublic Successful Response
   * @throws ApiError
   */
  public static readOrganizations(
    data: OrganizationsReadOrganizationsData = {},
  ): CancelablePromise<OrganizationsReadOrganizationsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/organizations/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Organization
   * Create new organization.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns OrganizationPublic Successful Response
   * @throws ApiError
   */
  public static createOrganization(
    data: OrganizationsCreateOrganizationData,
  ): CancelablePromise<OrganizationsCreateOrganizationResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/organizations/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Organization
   * Get organization by ID.
   * @param data The data for the request.
   * @param data.id
   * @returns OrganizationPublic Successful Response
   * @throws ApiError
   */
  public static readOrganization(
    data: OrganizationsReadOrganizationData,
  ): CancelablePromise<OrganizationsReadOrganizationResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/organizations/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Organization
   * Update an organization.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns OrganizationPublic Successful Response
   * @throws ApiError
   */
  public static updateOrganization(
    data: OrganizationsUpdateOrganizationData,
  ): CancelablePromise<OrganizationsUpdateOrganizationResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/organizations/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Organization
   * Delete an organization.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteOrganization(
    data: OrganizationsDeleteOrganizationData,
  ): CancelablePromise<OrganizationsDeleteOrganizationResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/organizations/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * Health check endpoint.
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}

export class WorkflowsService {
  /**
   * Read Workflows
   * Retrieve workflows.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns WorkflowsPublic Successful Response
   * @throws ApiError
   */
  public static readWorkflows(
    data: WorkflowsReadWorkflowsData = {},
  ): CancelablePromise<WorkflowsReadWorkflowsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/workflows/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create Workflow
   * Create a workflow. It starts with an empty graph.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns WorkflowPublic Successful Response
   * @throws ApiError
   */
  public static createWorkflow(
    data: WorkflowsCreateWorkflowData,
  ): CancelablePromise<WorkflowsCreateWorkflowResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/workflows/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Workflow
   * Get a workflow together with its full graph.
   * @param data The data for the request.
   * @param data.id
   * @returns WorkflowDetailPublic Successful Response
   * @throws ApiError
   */
  public static readWorkflow(
    data: WorkflowsReadWorkflowData,
  ): CancelablePromise<WorkflowsReadWorkflowResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/workflows/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Workflow
   * Update a workflow's metadata (not its graph).
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns WorkflowPublic Successful Response
   * @throws ApiError
   */
  public static updateWorkflow(
    data: WorkflowsUpdateWorkflowData,
  ): CancelablePromise<WorkflowsUpdateWorkflowResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/workflows/{id}",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Workflow
   * Delete a workflow and, by cascade, its nodes, edges and runs.
   * @param data The data for the request.
   * @param data.id
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteWorkflow(
    data: WorkflowsDeleteWorkflowData,
  ): CancelablePromise<WorkflowsDeleteWorkflowResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/workflows/{id}",
      path: {
        id: data.id,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Workflow Graph
   * Replace a workflow's graph in one transaction.
   *
   * Rejects the save with 400 when the graph is not a DAG, when an edge points at
   * a node outside the graph, or when an edge is type-incompatible.
   * @param data The data for the request.
   * @param data.id
   * @param data.requestBody
   * @returns WorkflowGraphPublic Successful Response
   * @throws ApiError
   */
  public static updateWorkflowGraph(
    data: WorkflowsUpdateWorkflowGraphData,
  ): CancelablePromise<WorkflowsUpdateWorkflowGraphResponse> {
    return __request(OpenAPI, {
      method: "PUT",
      url: "/api/v1/workflows/{id}/graph",
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}
