// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

/**
 * Generic single-message response body, returned by endpoints that only need
 * to report the outcome of the action they performed.
 */
export type Message = {
  message: string
}

/**
 * Properties to receive via API on update
 */
export type NewPassword = {
  token: string
  new_password: string
}

/**
 * Shared properties
 */
export type OrganizationBase = {
  title: string
  description?: string | null
}

/**
 * Properties to return via API, id is always required
 */
export type OrganizationPublic = {
  title: string
  description?: string | null
  id?: string | null
  owner_id?: string | null
}

/**
 * Properties to return via API, id is always required
 */
export type OrganizationsPublic = {
  data: Array<OrganizationPublic>
  count: number
}

/**
 * Properties to receive on item update
 */
export type OrganizationUpdate = {
  title?: string | null
  description?: string | null
}

/**
 * Model for creating a new user via private API.
 */
export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

/**
 * JSON payload containing access token
 */
export type Token = {
  access_token: string
  token_type?: string
}

/**
 * Properties to receive via API on update password
 */
export type UpdatePassword = {
  current_password: string
  new_password: string
}

/**
 * Properties to receive via API on creation
 */
export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

/**
 * Properties to return via API, id is always required
 */
export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

/**
 * Properties to receive via API on registration
 */
export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

/**
 * Properties to return via API, id is always required
 */
export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

/**
 * Properties to receive via API on update, all are optional
 */
export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

/**
 * Properties to receive via API on update, all are optional
 */
export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

/**
 * Properties to receive on workflow creation
 */
export type WorkflowCreate = {
  name: string
  description?: string | null
  active?: boolean
  settings?: {
    [key: string]: unknown
  } | null
}

/**
 * A workflow plus its full graph, returned by GET /workflows/{id} so the
 * editor loads everything in one request.
 */
export type WorkflowDetailPublic = {
  name: string
  description?: string | null
  active?: boolean
  settings?: {
    [key: string]: unknown
  } | null
  id?: string | null
  owner_id?: string | null
  version?: number | null
  created_at?: string | null
  updated_at?: string | null
  nodes?: Array<WorkflowNodePublic>
  edges?: Array<WorkflowEdgePublic>
}

/**
 * Properties to receive when saving an edge
 */
export type WorkflowEdgeCreate = {
  source_node_id: string
  target_node_id: string
  source_handle?: string
  target_handle?: string
  id?: string | null
}

/**
 * Properties to return via API, id is always required
 */
export type WorkflowEdgePublic = {
  source_node_id: string
  target_node_id: string
  source_handle?: string
  target_handle?: string
  id: string
  workflow_id: string
}

/**
 * Pydantic-style spec for one field of a node's input or output.
 *
 * A node declares its input and output as ``{field_name: WorkflowFieldSpec}``.
 * The allowed ``type`` values mirror the common Pydantic annotations GenAlima
 * uses: str, int, float, bool, list, dict, datetime, Any. ``items`` names the
 * element type when ``type`` is "list".
 *
 * Invariants enforced here: the type must come from the known vocabulary, and
 * `required` follows Pydantic semantics — leave it unset and it resolves to
 * false when a `default` is given, true otherwise. Stating `required: true`
 * alongside a default is rejected as contradictory.
 */
export type WorkflowFieldSpec = {
  type?: string
  /**
   * Resolved automatically: false when a default is set, else true.
   */
  required?: boolean | null
  default?: unknown | null
  description?: string | null
  enum?: Array<unknown> | null
  items?: string | null
}

/**
 * Payload for the transactional graph upsert: the full node and edge set of a
 * workflow. Anything missing from these lists is deleted by the route.
 */
export type WorkflowGraphIn = {
  nodes: Array<WorkflowNodeCreate>
  edges: Array<WorkflowEdgeCreate>
}

/**
 * Canonical graph returned after a save so the client can reconcile ids
 */
export type WorkflowGraphPublic = {
  id: string
  version: number
  nodes: Array<WorkflowNodePublic>
  edges: Array<WorkflowEdgePublic>
}

/**
 * Properties to receive when saving a node. The id is generated by the client
 * so edges can reference a node before it has been persisted; the server fills
 * it in when omitted.
 */
export type WorkflowNodeCreate = {
  key: string
  name: string
  type?: string
  type_version?: number
  position_x?: number
  position_y?: number
  disabled?: boolean
  code?: string
  input?: {
    [key: string]: WorkflowFieldSpec
  }
  output?: {
    [key: string]: WorkflowFieldSpec
  }
  type_enforcement?: string
  parameters?: {
    [key: string]: unknown
  }
  notes?: string | null
  id?: string | null
}

/**
 * Properties to return via API, id is always required
 */
export type WorkflowNodePublic = {
  key: string
  name: string
  type?: string
  type_version?: number
  position_x?: number
  position_y?: number
  disabled?: boolean
  code?: string
  input?: {
    [key: string]: WorkflowFieldSpec
  }
  output?: {
    [key: string]: WorkflowFieldSpec
  }
  type_enforcement?: string
  parameters?: {
    [key: string]: unknown
  }
  notes?: string | null
  id: string
  workflow_id: string
}

/**
 * Properties to return via API, id is always required
 */
export type WorkflowPublic = {
  name: string
  description?: string | null
  active?: boolean
  settings?: {
    [key: string]: unknown
  } | null
  id?: string | null
  owner_id?: string | null
  version?: number | null
  created_at?: string | null
  updated_at?: string | null
}

/**
 * Properties to return via API for workflow listing
 */
export type WorkflowsPublic = {
  data: Array<WorkflowPublic>
  count: number
}

/**
 * Properties to receive on workflow update
 */
export type WorkflowUpdate = {
  name?: string | null
  description?: string | null
  active?: boolean | null
  settings?: {
    [key: string]: unknown
  } | null
}

export type ServeIndexResponse = unknown

export type ServeIndex1Response = unknown

export type ServeIndex2Response = unknown

export type ServeIndex3Response = unknown

export type ServeIndex4Response = unknown

export type ServeIndex5Response = unknown

export type ServeIndex6Response = unknown

export type ServeIndex7Response = unknown

export type ServeIndex8Response = unknown

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type OrganizationsReadOrganizationsData = {
  limit?: number
  skip?: number
}

export type OrganizationsReadOrganizationsResponse = OrganizationsPublic

export type OrganizationsCreateOrganizationData = {
  requestBody: OrganizationBase
}

export type OrganizationsCreateOrganizationResponse = OrganizationPublic

export type OrganizationsReadOrganizationData = {
  id: string
}

export type OrganizationsReadOrganizationResponse = OrganizationPublic

export type OrganizationsUpdateOrganizationData = {
  id: string
  requestBody: OrganizationUpdate
}

export type OrganizationsUpdateOrganizationResponse = OrganizationPublic

export type OrganizationsDeleteOrganizationData = {
  id: string
}

export type OrganizationsDeleteOrganizationResponse = Message

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean

export type WorkflowsReadWorkflowsData = {
  limit?: number
  skip?: number
}

export type WorkflowsReadWorkflowsResponse = WorkflowsPublic

export type WorkflowsCreateWorkflowData = {
  requestBody: WorkflowCreate
}

export type WorkflowsCreateWorkflowResponse = WorkflowPublic

export type WorkflowsReadWorkflowData = {
  id: string
}

export type WorkflowsReadWorkflowResponse = WorkflowDetailPublic

export type WorkflowsUpdateWorkflowData = {
  id: string
  requestBody: WorkflowUpdate
}

export type WorkflowsUpdateWorkflowResponse = WorkflowPublic

export type WorkflowsDeleteWorkflowData = {
  id: string
}

export type WorkflowsDeleteWorkflowResponse = Message

export type WorkflowsUpdateWorkflowGraphData = {
  id: string
  requestBody: WorkflowGraphIn
}

export type WorkflowsUpdateWorkflowGraphResponse = WorkflowGraphPublic
