"""add meta in knowledge model

Revision ID: 088b512b6a7b
Revises: 7efd58dc74d8
Create Date: 2025-04-29 08:51:59.343989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '088b512b6a7b'
down_revision = '7efd58dc74d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.add_column('knowledge', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge', 'meta')
    op.drop_column('knowledge', 'source_type')
    # ### end Alembic commands ###
