"""Add knowledge file foriegn key added

Revision ID: 2ac74d1818a9
Revises: 7a8e9df57eb0
Create Date: 2025-08-09 02:33:06.174778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ac74d1818a9'
down_revision = '7a8e9df57eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('knowledge_file_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'knowledge', 'knowledgefile', ['knowledge_file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge', type_='foreignkey')
    op.drop_column('knowledge', 'knowledge_file_id')
    # ### end Alembic commands ###
