"""add meta_data in Message

Revision ID: 3459a4f8ed6e
Revises: 2ac74d1818a9
Create Date: 2025-08-11 03:52:53.840733

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3459a4f8ed6e'
down_revision = '2ac74d1818a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'meta_data')
    # ### end Alembic commands ###
