"""Add meta_data and owner_id to Connector model

Revision ID: 397c29749f1e
Revises: 3459a4f8ed6e
Create Date: 2025-08-27 18:37:52.088682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '397c29749f1e'
down_revision = '3459a4f8ed6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('connector', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'connector', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connector', type_='foreignkey')
    op.drop_column('connector', 'owner_id')
    op.drop_column('connector', 'meta_data')
    # ### end Alembic commands ###
