"""Add knowledge file table

Revision ID: 7a8e9df57eb0
Revises: c8f0edd6c489
Create Date: 2025-08-09 02:27:09.767244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a8e9df57eb0'
down_revision = 'c8f0edd6c489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgefile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('knowledge_owner_id_fkey', 'knowledge', type_='foreignkey')
    op.drop_column('knowledge', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('knowledge_owner_id_fkey', 'knowledge', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_table('knowledgefile')
    # ### end Alembic commands ###
