"""added owner_id in message model

Revision ID: c190f0197334
Revises: fb9d0a59c887
Create Date: 2025-05-09 17:04:56.517386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c190f0197334'
down_revision = 'fb9d0a59c887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'message', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'owner_id')
    # ### end Alembic commands ###
