"""remove extra column in knowledge model

Revision ID: c8f0edd6c489
Revises: 088b512b6a7b
Create Date: 2025-04-29 08:53:32.937635

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c8f0edd6c489'
down_revision = '088b512b6a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge', 'page_number')
    op.drop_column('knowledge', 'chunk_number')
    op.drop_column('knowledge', 'category')
    op.drop_column('knowledge', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('knowledge', sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('knowledge', sa.Column('chunk_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('knowledge', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
