"""template length

Revision ID: e96c840e9cbe
Revises: 3234c59f5362
Create Date: 2025-02-16 21:15:55.410670

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e96c840e9cbe'
down_revision = '3234c59f5362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template', 'template',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=4096),
               existing_nullable=True)
    op.drop_column('template', 'instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('instructions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('template', 'template',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=4096),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
