"""init migration

Revision ID: fb9d0a59c887
Revises: 7efd58dc74d8
Create Date: 2025-05-09 14:52:13.348541

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fb9d0a59c887'
down_revision = '7efd58dc74d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
