/**
 * Workflow API client.
 *
 * Hand-written rather than generated on purpose. `src/client` is generated by
 * `npm run generate-client`, but `frontend/openapi.json` is gitignored and the
 * spec currently exposes fewer routers than the frontend consumes (the
 * connectors/knowledges services only exist in the committed client). Running
 * the generator would therefore delete services other pages still import.
 *
 * This module reuses the generated `OpenAPI` config and request core, so auth
 * (`OpenAPI.TOKEN`), base URL and `ApiError` handling are identical to the rest
 * of the app. Delete it and go back to the generated client once the backend
 * exposes every router the frontend uses.
 */
import type { CancelablePromise } from "../../client/core/CancelablePromise"
import { OpenAPI } from "../../client/core/OpenAPI"
import { request } from "../../client/core/request"

/* ------------------------------------------------------------------ types */

/** Pydantic-style spec for one field of a node's input or output. */
export type WorkflowFieldSpec = {
  type?: string
  required?: boolean | null
  default?: unknown
  description?: string | null
  enum?: unknown[] | null
  items?: string | null
}

export type WorkflowNodeCreate = {
  id?: string | null
  key: string
  name: string
  type?: string
  type_version?: number
  position_x?: number
  position_y?: number
  disabled?: boolean
  code?: string
  input?: Record<string, WorkflowFieldSpec>
  output?: Record<string, WorkflowFieldSpec>
  type_enforcement?: string
  parameters?: Record<string, unknown>
  notes?: string | null
}

export type WorkflowEdgeCreate = {
  id?: string | null
  source_node_id: string
  target_node_id: string
  source_handle?: string
  target_handle?: string
  /**
   * `{target_field: source_field}` — which key of the source output feeds which
   * key of the target input. Strict: only the named pairs flow, so `{}` carries
   * nothing.
   */
  mapping?: Record<string, string>
}

export type WorkflowGraphIn = {
  nodes: WorkflowNodeCreate[]
  edges: WorkflowEdgeCreate[]
}

export type WorkflowNodePublic = Omit<WorkflowNodeCreate, "id"> & {
  id: string
  workflow_id: string
}

export type WorkflowEdgePublic = Omit<WorkflowEdgeCreate, "id"> & {
  id: string
  workflow_id: string
}

export type WorkflowPublic = {
  id?: string | null
  name: string
  description?: string | null
  active?: boolean
  settings?: Record<string, unknown> | null
  owner_id?: string | null
  version?: number | null
  /** A published snapshot: readable, but never writable. */
  is_frozen?: boolean
  created_at?: string | null
  updated_at?: string | null
}

export type WorkflowDetailPublic = WorkflowPublic & {
  nodes?: WorkflowNodePublic[]
  edges?: WorkflowEdgePublic[]
}

export type WorkflowsPublic = {
  data: WorkflowPublic[]
  count: number
}

export type WorkflowGraphPublic = {
  id: string
  version: number
  nodes: WorkflowNodePublic[]
  edges: WorkflowEdgePublic[]
}

/**
 * One published, immutable version of a workflow.
 *
 * `input` and `output` are the version's public contract, copied from the
 * snapshot's entry and exit node, so a client can render the component without
 * loading its graph.
 */
export type WorkflowComponentPublic = {
  id: string
  name: string
  description?: string | null
  owner_id: string
  version: number
  snapshot_workflow_id: string
  source_workflow_id?: string | null
  input?: Record<string, WorkflowFieldSpec>
  output?: Record<string, WorkflowFieldSpec>
  release_notes?: string | null
  created_at: string
}

export type WorkflowComponentsPublic = {
  data: WorkflowComponentPublic[]
  count: number
}

export type WorkflowComponentPublishIn = {
  name: string
  version: number
  description?: string | null
  release_notes?: string | null
  /** The canvas to save before snapshotting; omit to publish the saved graph. */
  graph?: WorkflowGraphIn | null
}

/* ------------------------------------------------------------------- calls */

const BASE_URL = "/api/v1/workflows"

export const WorkflowsService = {
  /** Paginated, owner-scoped list. */
  readWorkflows(
    data: { skip?: number; limit?: number } = {},
  ): CancelablePromise<WorkflowsPublic> {
    return request<WorkflowsPublic>(OpenAPI, {
      method: "GET",
      url: `${BASE_URL}/`,
      query: { skip: data.skip, limit: data.limit },
      errors: { 422: "Validation Error" },
    })
  },

  /** Create a workflow; it starts with an empty graph. */
  createWorkflow(data: {
    requestBody: { name: string; description?: string | null }
  }): CancelablePromise<WorkflowPublic> {
    return request<WorkflowPublic>(OpenAPI, {
      method: "POST",
      url: `${BASE_URL}/`,
      body: data.requestBody,
      mediaType: "application/json",
      errors: { 422: "Validation Error" },
    })
  },

  /** A workflow plus its full graph. */
  readWorkflow(data: { id: string }): CancelablePromise<WorkflowDetailPublic> {
    return request<WorkflowDetailPublic>(OpenAPI, {
      method: "GET",
      url: `${BASE_URL}/{id}`,
      path: { id: data.id },
      errors: { 404: "Workflow not found" },
    })
  },

  /** Metadata only; the graph is saved by updateWorkflowGraph. */
  updateWorkflow(data: {
    id: string
    requestBody: {
      name?: string
      description?: string | null
      active?: boolean
      settings?: Record<string, unknown> | null
    }
  }): CancelablePromise<WorkflowPublic> {
    return request<WorkflowPublic>(OpenAPI, {
      method: "PUT",
      url: `${BASE_URL}/{id}`,
      path: { id: data.id },
      body: data.requestBody,
      mediaType: "application/json",
      errors: { 404: "Workflow not found", 422: "Validation Error" },
    })
  },

  deleteWorkflow(data: { id: string }): CancelablePromise<{ message: string }> {
    return request<{ message: string }>(OpenAPI, {
      method: "DELETE",
      url: `${BASE_URL}/{id}`,
      path: { id: data.id },
      errors: { 404: "Workflow not found" },
    })
  },

  /**
   * Transactional graph upsert. Rejects with 400 when the graph is cyclic or an
   * edge is type-incompatible; the error body carries per-edge reasons.
   */
  updateWorkflowGraph(data: {
    id: string
    requestBody: WorkflowGraphIn
  }): CancelablePromise<WorkflowGraphPublic> {
    return request<WorkflowGraphPublic>(OpenAPI, {
      method: "PUT",
      url: `${BASE_URL}/{id}/graph`,
      path: { id: data.id },
      body: data.requestBody,
      mediaType: "application/json",
      errors: { 400: "Invalid graph", 422: "Validation Error" },
    })
  },

  /**
   * Publish the workflow as a component version.
   *
   * The supplied graph is saved first so the snapshot matches the canvas. A 409
   * means the version already exists for this name in the organization; the
   * body carries the existing versions and a suggestion. A 400 means the graph
   * has no single entry or exit node.
   */
  publishWorkflow(data: {
    id: string
    requestBody: WorkflowComponentPublishIn
  }): CancelablePromise<WorkflowComponentPublic> {
    return request<WorkflowComponentPublic>(OpenAPI, {
      method: "POST",
      url: `${BASE_URL}/{id}/publish`,
      path: { id: data.id },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        400: "Invalid graph",
        403: "Published snapshots are read-only",
        409: "Version already exists",
        422: "Validation Error",
      },
    })
  },
}

/* --------------------------------------------------------------- components */

const COMPONENTS_URL = "/api/v1/components"

export const ComponentsService = {
  /** Component versions published by the caller's organization. */
  readComponents(
    data: { skip?: number; limit?: number } = {},
  ): CancelablePromise<WorkflowComponentsPublic> {
    return request<WorkflowComponentsPublic>(OpenAPI, {
      method: "GET",
      url: `${COMPONENTS_URL}/`,
      query: { skip: data.skip, limit: data.limit },
      errors: { 422: "Validation Error" },
    })
  },

  /** One published version, including its public contract. */
  readComponent(data: {
    id: string
  }): CancelablePromise<WorkflowComponentPublic> {
    return request<WorkflowComponentPublic>(OpenAPI, {
      method: "GET",
      url: `${COMPONENTS_URL}/{id}`,
      path: { id: data.id },
      errors: { 404: "Component not found" },
    })
  },

  deleteComponent(data: {
    id: string
  }): CancelablePromise<{ message: string }> {
    return request<{ message: string }>(OpenAPI, {
      method: "DELETE",
      url: `${COMPONENTS_URL}/{id}`,
      path: { id: data.id },
      errors: { 403: "Not enough permissions", 404: "Component not found" },
    })
  },
}
